<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="<?php echo $imageUrl;?>public/logo2.png" height="30"/>
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="http://www.liantu.com/" target="_blank">联图网首页</a></li>
                <li><a href="/news/detail/" target="_blank">帮助</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="javascript:;">
                        <?php echo $this->base_member->getUsername();?>
                        <span class="caret"></span>
                    </a>            
                    <ul class="dropdown-menu">
                        <li><a href="/passwd/change/">修改密码</a></li>
                        <li><a href="/logout/">退出</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>